version: 2
jobs:
  build:
    docker:
        - image: newnakashima/haskell:latest
    steps:
      - checkout
      - run:
          name: pwd
          command: pwd
      - run:
          name: tree
          command: tree
      - run:
          name: Make.
          command: make
      - run:
          name: Run tests.
          command: ./tests.sh

