version: 2
jobs:
  build:
    docker:
        - image: newnakashima/haskell:latest
    steps:
      - checkout
      - run:
          name: stack.
          command: stack install split
      - run:
          name: Make.
          command: cd botchi_c_3003 && make
      - run:
          name: Run tests.
          command: cd botchi_c_3003 && ./test.sh

