version: 2
jobs:
  build:
    docker:
        - image: newnakashima/haskell:latest
    steps:
      - checkout
      - run:
          name: Run tests.
          command: make
          command: ./tests.sh

