version: 2
jobs:
  build:
    docker:
        - image: newnakashima/haskell:latest
    steps:
      - checkout
      - run:
          name: "[botchi_c_3003] Make."
          command: cd botchi_c_3003 && make
      - run:
          name: "[botchi_c_3003] Run tests."
          command: cd botchi_c_3003 && ./test.sh
      - run:
          name: "[botchi_c_3002] Make."
          command: cd botchi_c_3002 && make
      - run:
          name: "[botchi_c_3002] Run tests."
          command: cd botchi_c_3002 && ./test.sh

